CREATE TABLE [dbo].[Alcohol]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Category] NVARCHAR(255) NOT NULL,
	[Range] NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_Alcohol_Id PRIMARY KEY CLUSTERED (Id ASC)
)
