CREATE TABLE [dbo].[GrapeVariety]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Product_Id] INT NOT NULL,
	[Color] NVARCHAR(255) NOT NULL,
	[GrapeName] NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_GrapeVariety_Id PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT FK_GrapeVariety_Product_Id FOREIGN KEY (Product_Id) REFERENCES [Product]([Id])
)
