CREATE TABLE [dbo].[Supplier]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Address_Id] INT NOT NULL,
	[Legal] NVARCHAR(255) NOT NULL,
	[SocialReason] NVARCHAR(255) NOT NULL,
	[SIRET] NVARCHAR(255) NOT NULL,
	[APE_NAF] NVARCHAR(255) NOT NULL,
	[TVA] NVARCHAR(255) NOT NULL,
	[Manager] NVARCHAR(255) NOT NULL,
	[Phone] NVARCHAR(15) NOT NULL,
	[Email] NVARCHAR(255),
	CONSTRAINT PK_Supplier_Id PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT FK_Supplier_AddressId FOREIGN KEY (Address_Id) REFERENCES [Address]([Id])
)
